source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
target “BestDriverTitan” do

pod 'ChameleonFramework'
pod 'SVProgressHUD', '1.0'
pod 'AFNetworking', '~> 3.0'
pod 'HYBUnicodeReadable'
pod 'MMDrawerController', '~> 0.5.7'

pod "AsyncDisplayKit", ’1.9.5’

end
