source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
target “BestDriverTitan” do

pod 'IQKeyboardManager'

pod 'ChameleonFramework'
pod 'SVProgressHUD'
pod 'MBProgressHUD'
pod 'AFNetworking', '~> 3.0'
pod 'HYBUnicodeReadable'
pod 'MMDrawerController', '~> 0.5.7'

pod 'SDWebImage'

pod "AsyncDisplayKit", ’1.9.5’

pod 'pop', '~> 1.0'
#pod 'MLeaksFinder'

pod 'YYModel'

#蒲公英开放平台
pod 'Pgyer'
pod 'PgyUpdate'

#友盟统计开放平台
pod 'UMengAnalytics'#标准SDK，含IDFA

end
